# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fp_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
import sys


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(532, 543)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(40, 20, 451, 410))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()

        self.tab.setObjectName("tab")
        self.formLayout = QtWidgets.QFormLayout(self.tab)
        self.formLayout.setObjectName("formLayout")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setObjectName("pushButton_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setObjectName("pushButton_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pushButton_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setObjectName("pushButton_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pushButton_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(self.cost_float)
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.pushButton_6)
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setObjectName("textBrowser")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.textBrowser)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()

        self.tab_2.setObjectName("tab_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(90, 10, 346, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 40, 75, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 70, 75, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 100, 75, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 130, 75, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(90, 40, 346, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_8.setGeometry(QtCore.QRect(90, 70, 346, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_9.setGeometry(QtCore.QRect(90, 100, 346, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_10.setGeometry(QtCore.QRect(90, 130, 346, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_12.setGeometry(QtCore.QRect(10, 160, 427, 23))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_12.clicked.connect(self.face_float)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 190, 427, 193))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()

        self.tab_3.setObjectName("tab_3")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_13.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_14.setGeometry(QtCore.QRect(10, 40, 75, 23))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_15.setGeometry(QtCore.QRect(10, 70, 75, 23))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_16.setGeometry(QtCore.QRect(10, 100, 75, 23))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_17.setGeometry(QtCore.QRect(10, 130, 75, 23))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_18.setGeometry(QtCore.QRect(10, 160, 75, 23))
        self.pushButton_18.setObjectName("pushButton_18")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_11.setGeometry(QtCore.QRect(90, 10, 346, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_12.setGeometry(QtCore.QRect(90, 40, 346, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_13.setGeometry(QtCore.QRect(90, 70, 346, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_14.setGeometry(QtCore.QRect(90, 100, 346, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_15.setGeometry(QtCore.QRect(90, 130, 346, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_16.setGeometry(QtCore.QRect(90, 160, 346, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_19.setGeometry(QtCore.QRect(10, 190, 427, 23))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_19.clicked.connect(self.cent_commission_gmv)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser_3.setGeometry(QtCore.QRect(10, 220, 427, 151))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()

        self.tab_4.setObjectName("tab_4")
        self.pushButton_20 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_20.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_21.setGeometry(QtCore.QRect(10, 40, 75, 23))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_22.setGeometry(QtCore.QRect(10, 70, 75, 23))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_23.setGeometry(QtCore.QRect(10, 100, 75, 23))
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_24.setGeometry(QtCore.QRect(10, 130, 75, 23))
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_25.setGeometry(QtCore.QRect(10, 160, 75, 23))
        self.pushButton_25.setObjectName("pushButton_25")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_17.setGeometry(QtCore.QRect(90, 10, 346, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_18.setGeometry(QtCore.QRect(90, 40, 346, 20))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_19.setGeometry(QtCore.QRect(90, 70, 346, 20))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_20.setGeometry(QtCore.QRect(90, 100, 346, 20))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_21.setGeometry(QtCore.QRect(90, 130, 346, 20))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_22.setGeometry(QtCore.QRect(90, 160, 346, 20))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.pushButton_26 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_26.setGeometry(QtCore.QRect(10, 190, 427, 23))
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_26.clicked.connect(self.cent_commission_difference)
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.tab_4)
        self.textBrowser_4.setGeometry(QtCore.QRect(10, 220, 427, 151))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "福禄伙伴便捷计算器-v1.0"))
        self.tabWidget.setToolTip(_translate("Dialog", "<html><head/><body><p>成本上浮</p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "输入成本"))
        self.pushButton_2.setText(_translate("Dialog", "上浮费率"))
        self.pushButton_3.setText(_translate("Dialog", "服务费率"))
        self.pushButton_4.setText(_translate("Dialog", "输入面值"))
        self.pushButton_5.setText(_translate("Dialog", "浮动上限"))
        self.pushButton_6.setText(_translate("Dialog", "计算"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "成本上浮计算"))
        self.pushButton_7.setText(_translate("Dialog", "输入成本"))
        self.pushButton_8.setText(_translate("Dialog", "固定利润"))
        self.pushButton_9.setText(_translate("Dialog", "服务费率"))
        self.pushButton_10.setText(_translate("Dialog", "输入面值"))
        self.pushButton_11.setText(_translate("Dialog", "浮动上限"))
        self.pushButton_12.setText(_translate("Dialog", "计算"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "面值上浮计算"))
        self.pushButton_13.setText(_translate("Dialog", "输入密价"))
        self.pushButton_14.setText(_translate("Dialog", "输推广价"))
        self.pushButton_15.setText(_translate("Dialog", "输成本价"))
        self.pushButton_16.setText(_translate("Dialog", "输购买数"))
        self.pushButton_17.setText(_translate("Dialog", "平台费率"))
        self.pushButton_18.setText(_translate("Dialog", "分润比例"))
        self.pushButton_19.setText(_translate("Dialog", "计算"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "推广大使GMV分佣"))
        self.pushButton_20.setText(_translate("Dialog", "输入密价"))
        self.pushButton_21.setText(_translate("Dialog", "输推广价"))
        self.pushButton_22.setText(_translate("Dialog", "输成本价"))
        self.pushButton_23.setText(_translate("Dialog", "输购买数"))
        self.pushButton_24.setText(_translate("Dialog", "平台费率"))
        self.pushButton_25.setText(_translate("Dialog", "分润比例"))
        self.pushButton_26.setText(_translate("Dialog", "计算"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "推广大使差额比例分佣"))


        # 获取成本上浮参数值
    def cost_float(self):
        cost_price=self.dual_num(self.lineEdit.text())
        float_rate=self.dual_num(self.lineEdit_2.text())
        float_rate=float(float_rate/100)
        server_rate=self.dual_num(self.lineEdit_3.text())
        server_rate=float(server_rate/100)
        face_value=self.dual_num(self.lineEdit_4.text())
        float_max=self.dual_num(self.lineEdit_5.text())
        float_max=float(float_max/100)

        face_rate_value=face_value*float_max
        final_price=cost_price*(1+float_rate)/(1-server_rate)

        self.textBrowser.append("获取最终密价：{}".format(final_price))
        self.textBrowser.append("面值上浮价格：{}".format(face_rate_value))
        try:
            if final_price <= face_rate_value:
                self.textBrowser.append("密价小于上浮价格，按密价上浮，上浮价格：{}".format(final_price))
            else:
                self.textBrowser.append("密价大于上浮价格，按浮动上限，上浮价格：{}".format(face_rate_value))
        finally:
            self.textBrowser.append("*********************************************")


        # 获得面值上浮参数值
    def face_float(self):
        cost_price_1=self.dual_num(self.lineEdit_6.text())
        markup = self.dual_num(self.lineEdit_7.text())
        server_rate_2 = self.dual_num(self.lineEdit_8.text())
        server_rate_2 = float(server_rate_2 / 100)
        face_value = self.dual_num(self.lineEdit_9.text())
        float_max_2 = self.dual_num(self.lineEdit_10.text())
        float_max_2 = float(float_max_2 / 100)

        final_price1=(cost_price_1+markup)/(1-server_rate_2)
        face_rate_value2=(face_value*float_max_2)

        self.textBrowser_2.append("获取最终密价：{}".format(final_price1))
        self.textBrowser_2.append("面值上浮价格：{}".format(face_rate_value2))

        try:
            if final_price1 <= face_rate_value2:
                self.textBrowser_2.append("密价小于上浮价格，按密价上浮，上浮价格：{}".format(final_price1))
            else:
                self.textBrowser_2.append("密价大于上浮价格，按浮动上限，上浮价格：{}".format(face_rate_value2))
        finally:
            self.textBrowser_2.append("*********************************************")




        # 获得推广大使GMV分佣
    def cent_commission_gmv(self):
        close_price = self.dual_num(self.lineEdit_11.text())
        promotion_price=self.dual_num(self.lineEdit_12.text())
        cost_price_3 = self.dual_num(self.lineEdit_13.text())
        purchase_number = self.dual_num(self.lineEdit_14.text())
        platform_rate = self.dual_num(self.lineEdit_15.text())
        platform_rate=(platform_rate/100)
        allocation_ratio = self.dual_num(self.lineEdit_16.text())
        allocation_ratio=(allocation_ratio/100)

        #推广大使分佣
        promotion_ambassador=close_price*purchase_number*allocation_ratio

        #福禄伙伴利润
        pt=purchase_number*close_price*platform_rate
        fp=purchase_number*close_price*allocation_ratio
        fp_profit=close_price*purchase_number-cost_price_3*purchase_number-pt-fp

        self.textBrowser_3.append("推广大使分佣金额：{}".format(promotion_ambassador))
        self.textBrowser_3.append("福禄伙伴利润利润：{}".format(fp_profit))



        # 获得推广大使差额分佣
    def cent_commission_difference(self):
        close_price_4 = self.dual_num(self.lineEdit_11.text())
        promotion_price_4=self.dual_num(self.lineEdit_18.text())
        cost_price_4 = self.dual_num(self.lineEdit_19.text())
        purchase_number_4 = self.dual_num(self.lineEdit_20.text())
        platform_rate_4 = self.dual_num(self.lineEdit_21.text())
        platform_rate_4=(platform_rate_4/100)
        allocation_ratio_4 = self.dual_num(self.lineEdit_22.text())
        allocation_ratio_4=(allocation_ratio_4/100)

        #推广大使分佣
        promotion_ambassador1=(close_price_4-promotion_price_4)*allocation_ratio_4*purchase_number_4

        #福禄伙伴利润
        pt1=close_price_4*purchase_number_4*platform_rate_4
        fp1=(close_price_4-promotion_price_4)*allocation_ratio_4*purchase_number_4
        fp_profit1=close_price_4*purchase_number_4-cost_price_4*purchase_number_4-pt1-fp1

        self.textBrowser_4.append("推广大使分佣金额：{}".format(promotion_ambassador1))
        self.textBrowser_4.append("福禄伙伴利润利润：{}".format(fp_profit1))









    def dual_num(self,str):
        try:
            num = float(str)
        except Exception as e:
            num = 0
        return num











if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_Dialog()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
